version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
    links:
      - php
      - mysql
  php:
    build:
      context: ./docker/image
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
